import { createFileRoute, Link } from "@tanstack/react-router";

const CANONICAL = "https://carbon-craft-connect.lovable.app/privacy";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Evestime Invest" },
      {
        name: "description",
        content:
          "How Evestime Invest collects, uses, stores and protects your personal data across our copy trading and crypto research platform.",
      },
      { property: "og:title", content: "Privacy Policy — Evestime Invest" },
      {
        property: "og:description",
        content: "Read the Evestime Invest privacy policy: data we collect, how it's used and your rights.",
      },
      { property: "og:type", content: "website" },
      { property: "og:url", content: CANONICAL },
      { name: "twitter:card", content: "summary" },
      { name: "twitter:title", content: "Privacy Policy — Evestime Invest" },
      { name: "twitter:description", content: "How Evestime Invest handles your personal data." },
    ],
    links: [{ rel: "canonical", href: CANONICAL }],
  }),
  component: PrivacyPage,
});

const SECTIONS: { h: string; p: string }[] = [
  {
    h: "1. Information we collect",
    p: "We collect account information you provide (name, email, phone, ID documents for KYC), transactional information generated by your use of the platform (orders, copy allocations, deposits, withdrawals), and technical information (device, browser, IP, cookies).",
  },
  {
    h: "2. How we use information",
    p: "We use your information to operate and secure the platform, execute trades and copy allocations you request, verify identity, prevent fraud and abuse, communicate service updates and comply with legal and regulatory obligations.",
  },
  {
    h: "3. Legal basis",
    p: "We process personal data on the bases of contract performance, legitimate interest (product improvement and fraud prevention), legal obligation (KYC/AML) and, where required, your consent.",
  },
  {
    h: "4. Cookies & analytics",
    p: "We use strictly necessary cookies to run the site and analytics cookies to measure aggregate usage. You can control cookies in your browser at any time; disabling some may reduce functionality.",
  },
  {
    h: "5. Sharing & subprocessors",
    p: "We share information with regulated brokerage counterparties needed to execute your orders, identity-verification vendors, cloud hosting and analytics providers, and law enforcement where legally required.",
  },
  {
    h: "6. Data retention",
    p: "We retain personal data for the life of your account plus the period required by financial-services regulations (typically 5–10 years for transactional records).",
  },
  {
    h: "7. Your rights",
    p: "Subject to local law, you may request access, correction, deletion, portability or restriction of your personal data. Contact privacy@evestimeinvest.com to exercise these rights.",
  },
  {
    h: "8. Security",
    p: "We use encryption in transit and at rest, segregated bank accounts for client funds, and role-based access controls. No system is perfectly secure — please protect your credentials and enable 2FA.",
  },
  {
    h: "9. Contact",
    p: "Questions about this policy? Email privacy@evestimeinvest.com or write to Evestime Invest, Bahnhofstrasse 42, 8001 Zürich, Switzerland.",
  },
];

function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#0A0F1C] text-white font-sans">
      <header className="sticky top-0 z-50 border-b border-white/5 backdrop-blur bg-[#0A0F1C]/95">
        <div className="max-w-[1400px] mx-auto px-6 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="h-8 w-8 rounded-md bg-gradient-to-tr from-amber-300 to-blue-500 grid place-items-center font-black text-slate-900">
              E
            </div>
            <span className="font-bold tracking-wide">Evestime Invest</span>
          </Link>
          <nav className="text-sm text-slate-300 flex gap-5">
            <Link to="/" className="hover:text-white">Home</Link>
            <Link to="/about" className="hover:text-white">About</Link>
            <Link to="/terms" className="hover:text-white">Terms</Link>
          </nav>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <p className="text-amber-300 font-semibold tracking-widest text-xs uppercase">Legal</p>
        <h1 className="mt-3 text-4xl md:text-5xl font-extrabold">Privacy Policy</h1>
        <p className="mt-3 text-slate-400 text-sm">Last updated: January 2026</p>
        <p className="mt-6 text-slate-300 leading-relaxed">
          This Privacy Policy explains how Evestime Invest ("we", "our" or "us") collects and
          processes personal data when you use our website, mobile app and trading services.
          This is informational and does not constitute legal advice.
        </p>
        <div className="mt-10 space-y-8">
          {SECTIONS.map((s) => (
            <section key={s.h}>
              <h2 className="text-xl font-bold">{s.h}</h2>
              <p className="mt-2 text-slate-300 leading-relaxed">{s.p}</p>
            </section>
          ))}
        </div>
      </main>

      <footer className="border-t border-white/5 bg-[#050914]">
        <div className="max-w-[1400px] mx-auto px-6 py-6 flex flex-col md:flex-row items-center justify-between gap-3 text-xs text-slate-500">
          <p>© 2026 Evestime Invest. All rights reserved.</p>
          <div className="flex gap-5">
            <Link to="/about" className="hover:text-white">About</Link>
            <Link to="/terms" className="hover:text-white">Terms of Service</Link>
            <Link to="/" className="hover:text-white">Home</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
